export const FETCH_ANNONCEMENT_SUCCESS = "FETCH_ANNONCEMENT_SUCCESS";
export const FETCH_ANNONCEMENT_FAILURE = "FETCH_ANNONCEMENT_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const FETCH_SELECTED_ANNONCEMENT_SUCCESS =
  "FETCH_SELECTED_ANNONCEMENT_SUCCESS";
export const FETCH_SELECTED_ANNONCEMENT_FAILED =
  "FETCH_SELECTED_ANNONCEMENT_FAILED";
